quitOnTopLevelReturn: true
git:
  merging:
    args: "--no-ff"
  paging:
    colorArg: always
    pager: diff-so-fancy
  log:
    showGraph: 'always'
    showWholeGraph: true
  branchLogCmd: 'git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=oneline {{branchName}} --'
  allBranchesLogCmd: 'git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=oneline'
